### ISSUE TITLE
Pull in actual implementation

### ISSUE THREAD

**Issue by dbrnz** [opencor/libbondgraph#2]
Should the working [libbondgraph code](https://github.com/Jagirhussan/libbondgraph) not be pulled into this repo, so that it becomes a place to raise and discuss issues? @jagirhussan??

**Comment by Jagirhussan** [comment]
Hi David, Yes working code could be pulled into this repo. There is no resource commitment to maintain the repo, so merging pull requests can take a while.

**Comment by dbrnz** [comment]
Yes, please generate a PR from your working code repo -- I will merge it into this repo.

We then have an issue tracker available to discuss possible enhancements (in particular I'm wanting to have bond graph models to include `black-box` compartments that wrap CellML models).

**Comment by dbrnz** [comment]
Closed by PR #3.
